# Generated by Django 5.2.7 on 2025-10-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('ferret', 'Ferret'), ('tortoise', 'Tortoise'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('snake', 'Snake'), ('other', 'Other')], max_length=20),
        ),
    ]
